### ISSUE TITLE
Issues updating EntityReference in a Record

### ISSUE THREAD

**Issue by zaha** [RafaelCavazza/Xrm.Crm.WebApi#16]
Hi @RafaelCavazza,

I tried to update a Lead entity that has two custom Lookup fields for an entity called `tv_Language` like so:

```
var lead = new Entity("lead");
var language = new EntityReference("tv_language", new Guid("3D722FCA-7FB9-E711-80EC-3863BB34C940");
lead["tv_language"] = language;
lead["tv_spokenlanguage"] = language;

Guid guid = await webApi.CreateAsync(lead);
```

But when I do so, I receive the following exception:

> Can not add property tv_languages@odata.bind to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
>
>StackTrace:
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Xrm.Crm.WebApi.Request.RequestEntityParser.EntityToJObject(Entity entity, WebApiMetadata webApiMetadata) in D:\Workspace\GitHub\Xrm.Crm.WebApi\dotnet\Xrm.Crm.WebApi\Request\RequestEntityParser.cs:line 19
   at Xrm.Crm.WebApi.WebApi.CreateAsync(Entity entity) in D:\Workspace\GitHub\Xrm.Crm.WebApi\dotnet\Xrm.Crm.WebApi\WebApi.cs:line 42
   at TeamViewer.SalesLeads.CrmWebApi.SalesLeadRepository.CreateAsync(WebFormLead webFormLead) in D:\Workspace\D365\Web Services\Sales Leads Service\Persistence\TeamViewer.SalesLeads.CrmWebApi\SalesLeadRepository.cs:line 51
   at TeamViewer.SalesLeads.TestConsole.Program.MainAsync() in D:\Workspace\D365\Web Services\Sales Leads Service\Presentation\TeamViewer.SalesLeads.TestConsole\Program.cs:line 58
   at TeamViewer.SalesLeads.TestConsole.Program.Main(String[] args) in D:\Workspace\D365\Web Services\Sales Leads Service\Presentation\TeamViewer.SalesLeads.TestConsole\Program.cs:line 23

After a little bit of investigation I found that every type of entityreference is added to a dictionary, so if you have two lookup fields for the same entity type it will cause a duplicate key exception. Therefore, I uncommented one of the two lines but I still got an exception:

> An error occurred while validating input parameters: Microsoft.OData.ODataException: An undeclared property 'tv_languages' which only has property annotations in the payload but no property value was found in the payload. In OData, only declared navigation properties and declared named streams can be represented as properties without values.
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadUndeclaredProperty(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean propertyWithValue)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithoutValue(IODataJsonLightReaderResourceState resourceState, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass4_0.<ReadResourceContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)
   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
>
 >  StackTrace:
      at Xrm.Crm.WebApi.Response.ResponseValidator.EnsureSuccessStatusCode(HttpResponseMessage response, String jsonData) in D:\Workspace\GitHub\Xrm.Crm.WebApi\dotnet\Xrm.Crm.WebApi\Response\ResponseValidator.cs:line 30
   at Xrm.Crm.WebApi.WebApi.CreateAsync(Entity entity) in D:\Workspace\GitHub\Xrm.Crm.WebApi\dotnet\Xrm.Crm.WebApi\WebApi.cs:line 48
   at TeamViewer.SalesLeads.CrmWebApi.SalesLeadRepository.CreateAsync(WebFormLead webFormLead) in D:\Workspace\D365\Web Services\Sales Leads Service\Persistence\TeamViewer.SalesLeads.CrmWebApi\SalesLeadRepository.cs:line 51
   at TeamViewer.SalesLeads.TestConsole.Program.MainAsync() in D:\Workspace\D365\Web Services\Sales Leads Service\Presentation\TeamViewer.SalesLeads.TestConsole\Program.cs:line 58
   at TeamViewer.SalesLeads.TestConsole.Program.Main(String[] args) in D:\Workspace\D365\Web Services\Sales Leads Service\Presentation\TeamViewer.SalesLeads.TestConsole\Program.cs:line 23

Am I doing something fundamentally wrong here or is this a bug?

Cheers
Michael

**Comment by zaha** [comment]
@RafaelCavazza Any chance you can fix this soon?
Being able to set lookup fields is essential for my work.

**Comment by zaha** [comment]
Ok, I figured it out [after stumbling over this blog post here](https://community.dynamics.com/365/b/crmandcoffeethoughtsofanet/archive/2019/02/26/how-to-fix-getting-undeclared-property-error-when-using-lookups-with-dynamics-365-web-api): Apparently for lookup fields you have to use **the Schema Name, not the name of the field,** which has upper case characters in my case. So it works like this:

```
lead["tv_Language"] = language;
lead["tv_SpokenLanguage"] = language;
```

**But this is only true for lookup fields.** All the other fields have to be in lowercase!

This is really weird IMHO but not a problem with the lib.

**Comment by RafaelCavazza** [comment]
Hi @zaha!

Sorry I couldn't help in time.
We had some problems like these. 
Some fields have the same 'Schema Name' and 'Field Name'. Some don't.

I'm trying to implement a work around for this behaior.
The lib can download the metada and using the entity name plus the field name to find the Schema Name.
The only downside is it will take longer to load since it needs to download more data from the api.

I documented it on this issue:
https://github.com/RafaelCavazza/Xrm.Crm.WebApi/issues/3

But I din't had the time to implement. I'll try to get back to it.
